---
title: "Untitled"
output: html_document
date: "2023-09-25"
---

```{r}
library(tidyverse)
library(tidylog)
library(readxl) # to read in excel file
library(janitor) # for clean_names()
library(scales) # for pretty_breaks()
library(lemon) # for facet_rep_grid()

# Set plot theme
theme_set(theme_classic())
theme_update(panel.grid.major.y = element_line(),
             plot.title.position = "plot",
             plot.caption.position = "plot",
             strip.background = element_blank()) #,
        #     legend.box.background = element_rect(fill = "transparent", colour = NA),
        #     legend.background = element_rect(fill = "white", colour = "black"))

# Colourblind friendly palette
cbpal2 <- c("#601A4A","#63ACBE")
cbpal2a <- c("#E66100", "#5D3A9B")
```

## Data

```{r}
# Rate Ratios
rate_ratios <- read_xlsx("incidence_rate_ratios.xlsx") %>% 
  clean_names() %>% 
  mutate(age_group = factor(age_group, levels = c("0-4", "5-9", "10-14", "15-17")),
         outcome = factor(outcome, levels = c("mh_pres", "adhd_pres", "antidep_pres", "camhs_ref"), labels = c("MH Prescriptions", "ADHD Prescriptions", "Antidep Prescriptions", "CAMHS Referrals")),
         cpr_ratio = as.numeric(cpr_ratio),
         lower_ci = as.numeric(lower_ci),
         upper_ci = as.numeric(upper_ci))

# CAMHS Rates
camhs_rates <- read_xlsx("camhs_rates.xlsx") %>% 
  clean_names() %>% 
  mutate(age_group = factor(age_group, levels = c("0-4", "5-9", "10-14", "15-17")),
         camhs_ir = round(as.numeric(camhs_ir), digits = 1),
         cpr = factor(cpr, levels = c("0","1"), labels = c("Non-CPR", "CPR")))
```

## Plot IRRs

```{r}
rate_ratios %>% 
  ggplot(aes(x = age_group, y = cpr_ratio, colour = sex)) +
  geom_point(stat = "identity", position = position_dodge(width = .9)) +
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(width = .9)) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(breaks = pretty_breaks(10), limits = c(0,NA)) +
  scale_colour_manual(values = cbpal2, name = NULL) +
  facet_rep_wrap(~ outcome, ncol = 1) +
  labs(x = "Age Group (Years)\n", y = "\nIncidence Rate Ratio\nwith 95% Confidence Intervals") +
  coord_flip() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(),
        legend.position = "top",
        legend.margin = margin(0,0,0,0),
        legend.box.margin = margin(0,-15,-10,-10),
        panel.margin = unit(-.5,"lines"))

ggsave("rate ratios.png", dpi = 500, height = 8, width = 10)
```

## Separate Files

```{r}
outcomes <- levels(rate_ratios$outcome)

for (outcome_level in outcomes) {
  # Filter data for the current outcome level
  rate_ratios_filtered <- rate_ratios[rate_ratios$outcome == outcome_level, ]
  
  # Create the plot
  p <- ggplot(rate_ratios_filtered, aes(x = age_group, y = cpr_ratio, colour = sex)) +
  geom_point(stat = "identity", position = position_dodge(width = .9)) +
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(width = .9), width = 0.5) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(breaks = seq(0,9,1), limits = c(0,9.2)) +
  scale_colour_manual(values = cbpal2, name = NULL) +
  coord_flip() +
  labs(x = "Age Group (Years)\n", y = "\nIncidence Rate Ratio\nwith 95% Confidence Intervals") +
  theme(legend.position = "top")
  
  # Save the plot to a file (e.g., PNG)
  filename <- paste("plot_", outcome_level, ".png", sep = "")
  ggsave(filename, plot = p, width = 6, height = 4, dpi = 500)
}
```


## Plot CAMHS IRs

```{r}
camhs_rates %>% 
  ggplot(aes(x = age_group, y = camhs_ir, group = cpr, fill = cpr)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = cbpal2a, name = NULL) +
  scale_y_continuous(breaks = pretty_breaks(10)) +
  facet_rep_wrap(~sex) +
  labs(x = "\n Age Group (Years)", y = "Incidence Rate\nPer 1,000 Person-Years\n") +
  theme(legend.position = c(.15,.85),
        legend.text = element_text(size=rel(0.7)),
        legend.background = element_rect(fill = "white", colour = "black"))

ggsave("camhs rates.png", dpi = 500, height = 4, width = 7)
```

